import HealthKit

extension HKWorkoutActivityType {
    public var name: String {
        switch self {
        case .running:                       return "running"
        case .cycling:                       return "cycling"
        case .swimming:                      return "swimming"
        case .walking:                       return "walking"
        case .hiking:                        return "hiking"
        case .yoga:                          return "yoga"
        case .functionalStrengthTraining:    return "functionalStrengthTraining"
        case .traditionalStrengthTraining:   return "traditionalStrengthTraining"
        case .coreTraining:                  return "coreTraining"
        case .highIntensityIntervalTraining: return "highIntensityIntervalTraining"
        case .flexibility:                   return "flexibility"
        case .cooldown:                      return "cooldown"
        case .rowing:                        return "rowing"
        case .elliptical:                    return "elliptical"
        case .stairClimbing:                 return "stairClimbing"
        case .mixedCardio:                   return "mixedCardio"
        case .barre:                         return "barre"
        case .pilates:                       return "pilates"
        case .crossTraining:                 return "crossTraining"
        case .dance:                         return "dance"
        case .kickboxing:                    return "kickboxing"
        case .skatingSports:                 return "skatingSports"
        case .paddleSports:                  return "paddleSports"
        case .martialArts:                   return "martialArts"
        case .golf:                          return "golf"
        case .tennis:                        return "tennis"
        case .basketball:                    return "basketball"
        case .volleyball:                    return "volleyball"
        case .baseball:                      return "baseball"
        case .soccer:                        return "soccer"
        case .americanFootball:              return "americanFootball"
        case .hockey:                        return "hockey"
        case .lacrosse:                      return "lacrosse"
        case .rugby:                         return "rugby"
        case .softball:                      return "softball"
        case .waterFitness:                  return "waterFitness"
        case .waterPolo:                     return "waterPolo"
        case .waterSports:                   return "waterSports"
        case .boxing:                        return "boxing"
        case .climbing:                      return "climbing"
        case .equestrianSports:              return "equestrianSports"
        case .fishing:                       return "fishing"
        case .gymnastics:                    return "gymnastics"
        case .handCycling:                   return "handCycling"
        case .hunting:                       return "hunting"
        case .jumpRope:                      return "jumpRope"
        case .sailing:                       return "sailing"
        case .snowSports:                    return "snowSports"
        case .surfingSports:                 return "surfingSports"
        case .swimBikeRun:                   return "swimBikeRun"
        case .downhillSkiing:                return "downhillSkiing"
        case .crossCountrySkiing:            return "crossCountrySkiing"
        case .squash:                        return "squash"
        case .pickleball:                    return "pickleball"
        case .badminton:                     return "badminton"
        case .handball:                      return "handball"
        case .wheelchairWalkPace:            return "wheelchairWalkPace"
        case .wheelchairRunPace:             return "wheelchairRunPace"
        case .wrestling:                     return "wrestling"
        case .mindAndBody:                   return "mindAndBody"
        case .preparationAndRecovery:        return "preparationAndRecovery"
        case .australianFootball:            return "australianFootball"
        case .bowling:                       return "bowling"
        case .curling:                       return "curling"
        case .fencing:                       return "fencing"
        case .play:                          return "play"
        case .racquetball:                   return "racquetball"
        case .tableTennis:                   return "tableTennis"
        case .trackAndField:                 return "trackAndField"
        case .snowboarding:                  return "snowboarding"
        case .stairs:                        return "stairs"
        case .stepTraining:                  return "stepTraining"
        case .taiChi:                        return "taiChi"
        case .discSports:                    return "discSports"
        case .fitnessGaming:                 return "fitnessGaming"
        case .archery:                       return "archery"
        case .cricket:                       return "cricket"
        case .underwaterDiving:              return "underwaterDiving"
        case .transition:                    return "transition"
        case .cardioDance:                   return "cardioDance"
        case .socialDance:                   return "socialDance"
        case .other:                         return "other"
        default:                             return "other"
        }
    }
}
