import HealthKit

extension HKWorkoutActivityType {
    public var name: String {
        switch self {
        case .running: return "Running"
        case .cycling: return "Cycling"
        case .swimming: return "Swimming"
        case .walking: return "Walking"
        case .hiking: return "Hiking"
        case .yoga: return "Yoga"
        case .functionalStrengthTraining: return "Functional Strength Training"
        case .traditionalStrengthTraining: return "Traditional Strength Training"
        case .coreTraining: return "Core Training"
        case .highIntensityIntervalTraining: return "HIIT"
        case .flexibility: return "Flexibility"
        case .cooldown: return "Cooldown"
        case .rowing: return "Rowing"
        case .elliptical: return "Elliptical"
        case .stairClimbing: return "Stair Climbing"
        case .mixedCardio: return "Mixed Cardio"
        case .barre: return "Barre"
        case .pilates: return "Pilates"
        case .crossTraining: return "Cross Training"
        case .dance: return "Dance"
        case .kickboxing: return "Kickboxing"
        case .skatingSports: return "Skating"
        case .paddleSports: return "Paddle Sports"
        case .martialArts: return "Martial Arts"
        case .golf: return "Golf"
        case .tennis: return "Tennis"
        case .basketball: return "Basketball"
        case .volleyball: return "Volleyball"
        case .baseball: return "Baseball"
        case .soccer: return "Soccer"
        case .americanFootball: return "American Football"
        case .hockey: return "Hockey"
        case .lacrosse: return "Lacrosse"
        case .rugby: return "Rugby"
        case .softball: return "Softball"
        case .waterFitness: return "Water Fitness"
        case .waterPolo: return "Water Polo"
        case .waterSports: return "Water Sports"
        case .boxing: return "Boxing"
        case .climbing: return "Climbing"
        case .equestrianSports: return "Equestrian"
        case .fishing: return "Fishing"
        case .gymnastics: return "Gymnastics"
        case .handCycling: return "Hand Cycling"
        case .hunting: return "Hunting"
        case .jumpRope: return "Jump Rope"
        case .sailing: return "Sailing"
        case .snowSports: return "Snow Sports"
        case .surfingSports: return "Surfing"
        case .swimBikeRun: return "Triathlon"
        case .downhillSkiing: return "Downhill Skiing"
        case .crossCountrySkiing: return "Cross-Country Skiing"
        case .squash: return "Squash"
        case .pickleball: return "Pickleball"
        case .badminton: return "Badminton"
        case .handball: return "Handball"
        case .wheelchairWalkPace: return "Wheelchair Walk"
        case .wheelchairRunPace: return "Wheelchair Run"
        case .wrestling: return "Wrestling"
        case .mindAndBody: return "Mind & Body"
        case .preparationAndRecovery: return "Preparation & Recovery"
        // Additional activity types
        case .australianFootball: return "Australian Football"
        case .bowling:            return "Bowling"
        case .curling:            return "Curling"
        case .fencing:            return "Fencing"
        case .play:               return "Play"
        case .racquetball:        return "Racquetball"
        case .tableTennis:        return "Table Tennis"
        case .trackAndField:      return "Track and Field"
        case .snowboarding:       return "Snowboarding"
        case .stairs:             return "Stairs"
        case .stepTraining:       return "Step Training"
        case .taiChi:             return "Tai Chi"
        case .discSports:         return "Disc Sports"
        case .fitnessGaming:      return "Fitness Gaming"
        case .archery:            return "Archery"
        default: return "Other"
        }
    }
}
